news_sites:
  portafolio:
    url: https://www.portafolio.co
    queries:
      homepage_articles_links : '.title a'
      article_body : '.article-content'
      article_title: '.title'
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_articles_links : '.field-content a'
      article_body : '.field-name-body'
      article_title: '.pane-content h1'
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_articles_links : '.title-container a'
      article_body : '.contenido'
      article_title: '.titulo'